CoffeeShopEntityDatabase/Controllers/UserItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoffeeShopEntityDatabase.Models;

namespace CoffeeShopEntityDatabase.Controllers
{
    public class UserItemsController : Controller
    {
        private ShopDBEntities1 db = new ShopDBEntities1();

        // GET: UserItems
        public ActionResult Index()
        {
            var userItems = db.UserItems.Include(u => u.Item).Include(u => u.User);
            return View(userItems.ToList());
        }

        // GET: UserItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserItem userItem = db.UserItems.Find(id);
            if (userItem == null)
            {
                return HttpNotFound();
            }
            return View(userItem);
        }

        // GET: UserItems/Create
        public ActionResult Create()
        {
            ViewBag.UserItemID = new SelectList(db.Items, "Id", "ItemName");
            ViewBag.UserItemID = new SelectList(db.Users, "Id", "UserName");
            return View();
        }

        // POST: UserItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserItemID,UserID,ItemID")] UserItem userItem)
        {
            if (ModelState.IsValid)
            {
                db.UserItems.Add(userItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserItemID = new SelectList(db.Items, "Id", "ItemName", userItem.UserItemId);
            ViewBag.UserItemID = new SelectList(db.Users, "Id", "UserName", userItem.UserItemId);
            return View(userItem);
        }

        // GET: UserItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserItem userItem = db.UserItems.Find(id);
            if (userItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserItemID = new SelectList(db.Items, "Id", "ItemName", userItem.UserItemId);
            ViewBag.UserItemID = new SelectList(db.Users, "Id", "UserName", userItem.UserItemId);
            return View(userItem);
        }

        // POST: UserItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserItemID,UserID,ItemID")] UserItem userItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserItemID = new SelectList(db.Items, "Id", "ItemName", userItem.UserItemId);
            ViewBag.UserItemID = new SelectList(db.Users, "Id", "UserName", userItem.UserItemId);
            return View(userItem);
        }

        // GET: UserItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserItem userItem = db.UserItems.Find(id);
            if (userItem == null)
            {
                return HttpNotFound();
            }
            return View(userItem);
        }

        // POST: UserItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserItem userItem = db.UserItems.Find(id);
            db.UserItems.Remove(userItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoffeeShopEntityDatabase/Views/Shared/_Layout.cshtml
@using CoffeeShopEntityDatabase.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["User"] != null)
                    {
                        User u = (User)Session["User"];

                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Shop", "Shop", "Home")</li>
                        <li>@Html.ActionLink("List", "Index", "UserItems")</li>
                        <li>@Html.ActionLink("Details", "Details", "UserItems")</li>
                        <li>@Html.ActionLink("Delete", "Delete", "UserItems")</li>
                        <li style="color:white">@u.UserName has $ @u.Funds</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Register", "Register", "Home")</li>
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>